name: 'Style and documentation'
env:
  id: documentation

on: push

jobs:
  generic:
    runs-on: ubuntu-latest
    outputs:
      pull_request: ${{ steps.cpr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@master
      - name: Docs - Readme License
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/license.md
          target: SECURITY.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          branch: auto-${{env.id}}-${{github.ref}}

  terraform:
    needs: generic
    name: Style and documentation
    runs-on: ubuntu-latest
    outputs:
      pull_request: ${{ steps.cpr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@master
        if: ${{ needs.generic.outputs.pull_request > 0 }}
        with:
          ref: auto-${{env.id}}-${{github.ref}}

      - uses: actions/checkout@master
        if: ${{ needs.generic.outputs.pull_request == 0 }}

      - name: Docs - Readme PWD
        uses: olivr-com/inject-command-action@v1
        with:
          command: pwd | sed 's/\// /g'
          target: README.md
          force: true

      - name: Lint - Download config
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/linters/markdown/.markdownlint.yml

      - name: Docs - Code of Conduct
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/CODE_OF_CONDUCT.md

      - name: Docs - License
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/LICENSE

      - name: Docs - Readme License
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/license.md
          target: README.md

      - name: Lint - Markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          fix: true
          config: .markdownlint.yml

      - name: Lint - Cleanup
        run: rm -rf .markdownlint.yml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          branch: auto-${{env.id}}-${{github.ref}}

  finalize:
    needs: [generic, terraform]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@master
        if: ${{ needs.generic.outputs.pull_request > 0 || needs.terraform.outputs.pull_request > 0 }}
        env:
          pr_generic: ${{ needs.generic.outputs.pull_request || needs.terraform.outputs.pull_request }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github..pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env['pr_generic']
            })
