name: 'Style and documentation'

on: push

jobs:
  main:
    name: Style and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Lint - Download config
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/linters/markdown/.markdownlint.yml

      - name: Docs - Code of Conduct
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/docs/CODE_OF_CONDUCT.md

      - name: Docs - License
        uses: olivr-com/download-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/LICENSE

      - name: Docs - Readme License
        uses: olivr-com/inject-file-action@v1
        with:
          url: https://raw.githubusercontent.com/olivr-com/defaults/master/readme/license.md
          target: README.md

      - name: Docs - Readme PWD
        uses: olivr-com/inject-command-action@v1
        with:
          command: pwd | sed 's/\// /g'
          target: README.md
          force: true

      - name: Lint - Markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          fix: true
          config: .markdownlint.yml

      - name: Lint - Cleanup
        run: rm -rf .markdownlint.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Update documentation
          branch: ${{ github.head_ref }}
